### ISSUE TITLE
DS18B20 Question

### ISSUE THREAD

**Issue by JimOHern** [daveake/FlexTrack#13]
I have added a second temperature sensor and it is reflected in the serial console debug output but does not show up in the APRS.FI or HabHub information.  Is this normal or have I done something wrong?

#define EXTRA_FIELD_FORMAT    ",%d,%d,%d,%d,%d"          // List of formats for extra fields. Make empty if no such fields.  Always use comma at start of there are any such fields.
#define EXTRA_FIELD_LIST       ,DS18B20_Temperatures[0],DS18B20_Temperatures[1],(int)((GPS.Speed * 13) / 7), GPS.Direction, GPS.Satellites
#define SENTENCE_LENGTH      100                  // This is more than sufficient for the standard sentence.  Extend if needed; shorten if you are tight on memory.

**Comment by daveake** [comment]
That section is for RTTY and LoRa, and does not apply to APRS which uses 
a completely different encoding scheme.  The program only sends a single 
temperature in the APRS packets.  It may not be a huge task to add a 
second temperature, but the file to edit is aprs.ino not flextrack.ino.  
APRS parameters like this are sent as a value and also a parameter 
packet that tells the APRS system how to decode the telemetry, so both 
would need to change.
