### ISSUE TITLE
I2C Compile issues

### ISSUE THREAD

**Issue by robcollyer** [daveake/FlexTrack#14]
having installed libraries in the instructions and using the correct Arduino IDE 1.6.5 i get the following compile errors

gps.ino:14:19: fatal error: I2C.h: No such file or directory
compilation terminated.
Error compiling.

Any clues on which library is missing?

**Comment by daveake** [comment]
Sorry for delay, see readme which has been updated to answer this:

To build FlexTrack for use with a HABDuino or other tracker using I2C communications, you need to install this library into your Arduino IDE:

https://github.com/rambo/I2C
