### ISSUE TITLE
Undesirable Behaviour on loosing lock in GPS.ino

### ISSUE THREAD

**Issue by SteveRan** [daveake/FlexTrack#4]
On getting first valid 3D position ProcessUBX_NAV_SOL() sets "HaveHadALock" ProcessUBX_NAV_POSLLH() uses "HaveHadALock" to determine if it should write to "GPS.Longitude" "GPS.Latitude" and "GPS.Altitude" which are then subsequently used in the transmitted position.

If the GPS gets lock - but subsequently looses it (say on payload landing) the transmitted position will be whatever the GPS outputs without lock - which can often be significantly out from the actual position. Under loss of lock it would be better to transmit the last known good position.

Proposal: ProcessUBX_NAV_POSLLH() should qualify "HaveHadALock" with GPS.Lock >= 2 so that there is a least a valid 2d position before updating GPS.Longitude" "GPS.Latitude" and "GPS.Altitude".

**Comment by daveake** [comment]
Yeah good point, and I've been meaning to check as I couldn't remember if
I'd accounted for that.  Will get it sorted.

Dave

**Comment by SteveRan** [comment]
During ground testing I noticed when it lost lock it was outputting positions a few hundred meters away but at 36Km altitude!

```
Steve
```

On 5 Mar 2016, at 11:12, David Akerman notifications@github.com wrote:

> Yeah good point, and I've been meaning to check as I couldn't remember if
> I'd accounted for that. Will get it sorted.
> 
> Dave
> 
> On 5 March 2016 at 10:50, Steve Randall notifications@github.com wrote:
> 
> > On getting first valid 3D position ProcessUBX_NAV_SOL() sets
> > "HaveHadALock" ProcessUBX_NAV_POSLLH() uses "HaveHadALock" to determine if
> > it should write to "GPS.Longitude" "GPS.Latitude" and "GPS.Altitude" which
> > are then subsequently used in the transmitted position.
> > 
> > If the GPS gets lock - but subsequently looses it (say on payload landing)
> > the transmitted position will be whatever the GPS outputs without lock -
> > which can often be significantly out from the actual position. Under loss
> > of lock it would be better to transmit the last known good position.
> > 
> > Proposal: ProcessUBX_NAV_POSLLH() should qualify "HaveHadALock" with
> > GPS.Lock >= 2 so that there is a least a valid 2d position before updating
> > GPS.Longitude" "GPS.Latitude" and "GPS.Altitude".
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/daveake/FlexTrack/issues/4.
> > 
> > —
> > Reply to this email directly or view it on GitHub.

Steve Randall
Random Engineering Ltd
steve@randomaerospace.com
+44 7802 242135

**Comment by daveake** [comment]
If it did the same but 49km altitude I think it would have a customer :p

Dave

**Comment by daveake** [comment]
Done.  Now using UBX-NAV-PVT with fixtype 2-4 for lat/lon, and 3-4 for altitude.
