### ISSUE TITLE
Should FlexTrack work with LoRaArduinoSerial?

### ISSUE THREAD

**Issue by torntrousers** [daveake/FlexTrack#7]
Should this FlexTrack code work with your LoRaArduinoSerial code? I'm trying but can't get it to receive anything.

I'm using two DRF1278F Lora modules, do you know if they should work with this code?

I've tried running the Radiohead rf95_client/server code and that does work ok sending and receiving so I think the wiring between the DRF1278F and Arduino's must be ok.

I noticed LoRaArduinoSerial initialises Frequency=434.250 whereas FlexTrack defines LORA_FREQUENCY 434.450, but changing those to match doesn't seem to help.

The FlexTrack output I get is:
FlexTrack Flight Computer, payload ID(s) CHANGE_ME

I2C GPS
LoRa telemetry enabled
Free memory = 994
Setting LoRa Mode
LoRa Mode Set
Frequency is 434.45
FrequencyValue is 7118029
Setup Complete
LoRa is free
LoRa: Tx ASCII Sentence
Sending 57 bytes
Setting flight mode

**\* SetGNSSMode() ***
0:0:38 - 0.000000,0.000000,0,0
0:0:39 - 0.000000,0.000000,0,0
LoRa is free
LoRa: Tx ASCII Sentence
Sending 57 bytes
0:0:40 - 0.000000,0.000000,0,0
0:0:41 - 0.000000,0.000000,0,0
LoRa is free
LoRa: Tx ASCII Sentence
Sending 57 bytes
0:0:42 - 0.000000,0.000000,0,0
0:0:43 - 0.000000,0.000000,0,0
LoRa is free
... (then eventually...
LoRa: Tx ASCII Sentence
Sending 61 bytes
12:32:45 - 51.586822,-0.102293,12,7
12:32:46 - 51.586814,-0.102291,11,6
LoRa is free
LoRa: Tx ASCII Sentence
Sending 61 bytes
12:32:47 - 51.586811,-0.102290,11,6
12:32:48 - 51.586811,-0.102289,11,6
LoRa is free

and on the LoraArduinoSeial side just:

LoRa USB Receiver V1.0

FrequencyValue is 7118028
Setup Complete
CurrentRSSI=-119
CurrentRSSI=-48
CurrentRSSI=-47
CurrentRSSI=-49
CurrentRSSI=-47
... etc

Any ideas on what could be wrong or how to debug?

**Comment by daveake** [comment]
1 - Make sure you're using the same lora settings on tx and rx
2 - Try retuning one side or the other up or down 1-5kHz, in steps.

In general these modules are not very accurately tuned.
