### ISSUE TITLE
ADC battery level /  resistors

### ISSUE THREAD

**Issue by sp2ong** [daveake/FlexTrack#8]
I have see in config that for measurement battery level is used MULTIPLIER 4.9

 #define A0_MULTIPLIER 4.9

What values are used 2 resistors connected to A0 ???

VCC    <-------[ R1 ]-------+-----[ R2 ] ------> GND
     A0  <.............................|

I will be use battery 3.7V connected to RAW arduino ProMini 

Waldek SP2ONG

**Comment by daveake** [comment]
I just run it, compare the reported voltage with that measured on a DMM, 
then adjust the multiplier to suit.
